"use client";
import { useRef, useState } from "react";
import { BarChart3, Download, Eye, FileImage, KeyRound, LockKeyhole, ScanLine, ShieldCheck, Upload } from "lucide-react";

declare global { interface Window { gtag?: (...args: unknown[]) => void } }

const stats = [{label:"VISITS THIS MONTH",value:"—",note:"Connect analytics to measure"},{label:"IMAGES SCANNED",value:"—",note:"Live counter after setup"},{label:"CLEAN SCANS",value:"—",note:"Results stay private"}];
export default function Home() {
 const [mode,setMode]=useState<"hide"|"reveal">("hide"),[file,setFile]=useState<File|null>(null),[message,setMessage]=useState(""),[key,setKey]=useState(""),[notice,setNotice]=useState(""); const input=useRef<HTMLInputElement>(null);
 const pick=(f?:File)=>{if(f?.type.startsWith("image/")){setFile(f);setNotice("");}else if(f)setNotice("Please choose a PNG, JPG, or WebP image.");};
 const run=async()=>{if(!file)return setNotice("Choose an image first.");if(mode==="hide"&&!message.trim())return setNotice("Write a message to hide first.");const img=new Image();img.src=URL.createObjectURL(file);await new Promise(r=>img.onload=r);const c=document.createElement("canvas");c.width=img.width;c.height=img.height;const x=c.getContext("2d")!;x.drawImage(img,0,0);const d=x.getImageData(0,0,c.width,c.height);if(mode==="hide"){const bytes=new TextEncoder().encode(`STGW|${key}|${message}\0`);if(bytes.length*8>d.data.length/4*3)return setNotice("This message is too large for that image. Try a larger PNG.");let n=0;for(const b of bytes)for(let bit=7;bit>=0;bit--){const p=Math.floor(n/3)*4+n%3;d.data[p]=(d.data[p]&254)|((b>>bit)&1);n++;}x.putImageData(d,0,0);const a=document.createElement("a");a.href=c.toDataURL("image/png");a.download=`stega-${file.name.replace(/\.[^.]+$/,'')}.png`;a.click();window.gtag?.("event","stega_encode");setNotice("Encoded! Your PNG download has started.");}else{let bits="",out="";for(let i=0;i<d.data.length;i+=4){for(let k=0;k<3;k++){bits+=(d.data[i+k]&1);if(bits.length===8){const ch=String.fromCharCode(parseInt(bits,2));if(ch==="\0"){const parts=out.split("|");window.gtag?.("event","stega_scan");return setNotice(parts[0]==="STGW"?`Hidden message: ${parts.slice(2).join("|")||"(empty)"}`:"No compatible message found.");}out+=ch;bits="";}}}window.gtag?.("event","stega_scan");setNotice("No compatible message found.");}};
 return <main className="min-h-screen overflow-x-hidden bg-[#080a1d] text-[#eef2ff]"><div className="pointer-events-none fixed inset-0 arcade-grid opacity-40"/>
 <header className="relative border-b border-white/10 bg-[#0b0d25]/90 px-5 py-4 backdrop-blur sm:px-8"><div className="mx-auto flex max-w-7xl items-center justify-between gap-5"><a className="flex items-center gap-3" href="#workspace"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#ff3cac] text-[#080a1d] shadow-[0_0_22px_#ff3cac]"><Eye size={22}/></span><span><b className="block font-mono text-lg">STEGA_WHAT</b><small className="font-mono text-[10px] tracking-[.2em] text-cyan-300">SIGNAL LAB</small></span></a><div className="hidden gap-6 font-mono text-xs text-slate-300 md:flex"><a href="#workspace">WORKSPACE</a><a href="#activity">ACTIVITY</a><a href="#privacy">PRIVACY</a></div><span className="rounded-full border border-emerald-400/40 bg-emerald-400/10 px-3 py-1.5 font-mono text-[11px] text-emerald-300"><i className="mr-2 inline-block h-2 w-2 rounded-full bg-emerald-300"/>SYSTEM READY</span></div></header>
 <section id="workspace" className="relative mx-auto max-w-7xl px-5 py-9 sm:px-8 lg:py-14"><div className="mb-8 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="mb-3 font-mono text-xs tracking-[.22em] text-cyan-300">PRIVATE IMAGE STEGANOGRAPHY</p><h1 className="text-4xl font-black leading-none sm:text-5xl">Hide the message.<br/><span className="text-[#ff3cac]">Keep the signal.</span></h1></div><p className="max-w-xs text-sm leading-6 text-slate-400">Embed a private note inside an image, or inspect one for a hidden payload. Your image stays in your browser until you choose to process it.</p></div>
 <div className="grid gap-5 lg:grid-cols-[1fr_350px]"><section className="panel overflow-hidden rounded-2xl border border-white/10"><div className="flex border-b border-white/10 p-2"><button onClick={()=>{setMode("hide");setNotice("");}} className={'tab '+(mode==='hide'?'tab-on':'')}><LockKeyhole size={16}/> HIDE A MESSAGE</button><button onClick={()=>{setMode("reveal");setNotice("");}} className={'tab '+(mode==='reveal'?'tab-on':'')}><ScanLine size={16}/> REVEAL A MESSAGE</button></div><div className="grid gap-6 p-5 sm:p-7 md:grid-cols-2"><div><label className="label">01 / CARRIER IMAGE</label><button onClick={()=>input.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();pick(e.dataTransfer.files[0]);}} className="dropzone mt-3 w-full"><Upload size={28} className="text-cyan-300"/><b>{file?file.name:"Drop an image here"}</b><span>{file?`${Math.ceil(file.size/1024)} KB ready`:"or select a PNG, JPG, or WebP"}</span></button><input ref={input} type="file" accept="image/png,image/jpeg,image/webp" className="hidden" onChange={e=>pick(e.target.files?.[0])}/></div><div className="flex flex-col">{mode==="hide"?<><label className="label">02 / SECRET MESSAGE</label><textarea value={message} onChange={e=>setMessage(e.target.value)} maxLength={1000} className="field mt-3 min-h-32 flex-1 resize-none" placeholder="Type what only your recipient should know…"/><span className="mt-2 text-right font-mono text-[11px] text-slate-500">{message.length}/1000</span></>:<div className="rounded-xl border border-dashed border-white/10 bg-white/[.025] p-6 text-sm leading-6 text-slate-400"><ScanLine className="mb-4 text-[#ff3cac]"/><b className="block text-slate-200">Ready to inspect</b>We’ll look for a compatible embedded message in your selected image.</div>}</div><div className="md:col-span-2"><label className="label">03 / OPTIONAL PASSPHRASE</label><div className="mt-3 flex gap-3"><div className="relative flex-1"><KeyRound className="absolute left-3 top-3 text-slate-500" size={17}/><input value={key} onChange={e=>setKey(e.target.value)} className="field w-full pl-10" placeholder="Add a key for your recipient" type="password"/></div><button onClick={run} className="arcade-btn">{mode==="hide"?<><Download size={17}/> ENCODE IMAGE</>:<><ScanLine size={17}/> SCAN IMAGE</>}</button></div>{notice&&<p aria-live="polite" className="mt-3 text-sm text-cyan-200">{notice}</p>}</div></div></section>
 <aside id="activity" className="panel rounded-2xl border border-white/10 p-5 sm:p-6"><div className="mb-6 flex items-center justify-between"><div><p className="label">PULSE CHECK</p><h2 className="mt-2 text-xl font-bold">Monthly activity</h2></div><BarChart3 className="text-[#ff3cac]"/></div><div className="space-y-3">{stats.map(s=><div key={s.label} className="rounded-xl border border-white/8 bg-white/[.025] p-4"><p className="font-mono text-[10px] tracking-wider text-slate-500">{s.label}</p><strong className="mt-1 block text-2xl text-white">{s.value}</strong><small className="text-xs text-slate-500">{s.note}</small></div>)}</div><p className="mt-5 border-t border-white/10 pt-4 text-xs leading-5 text-slate-500">Counts stay blank until analytics is connected—no made-up visitor data.</p></aside></div></section>
 <section id="privacy" className="relative border-y border-white/10 bg-[#101438] px-5 py-8 sm:px-8"><div className="mx-auto grid max-w-7xl gap-5 md:grid-cols-3"><div><p className="label">BUILT FOR DISCRETION</p><h2 className="mt-3 text-2xl font-bold">Clear controls, quiet handling.</h2></div><div className="info"><ShieldCheck className="text-emerald-300"/><b>Privacy first</b><span>Never use a secret you cannot safely share with the intended recipient.</span></div><div className="info"><FileImage className="text-cyan-300"/><b>Best results</b><span>PNG images preserve embedded pixel-level information most reliably.</span></div></div></section><footer className="relative mx-auto flex max-w-7xl justify-between px-5 py-7 font-mono text-[11px] text-slate-500 sm:px-8"><span>STEGA_WHAT / LOCAL SIGNAL TOOL</span><span>USE RESPONSIBLY · 2026</span></footer></main>;
}
